---
name: "Setup Mint"
author: Yevhen Fabizhevskyi
description: "This action sets up a Mint programming language."
branding:
  icon: feather
  color: green
inputs:
  version:
    description: "Mint version"
    required: false
    default: "0.19.0"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Collect info
      id: info
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: |
        echo "MINT_INSTALLED=$(if command -v mint >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
        mkdir -p "$GITHUB_WORKSPACE/mint"
        echo "MINT_PATH=$GITHUB_WORKSPACE/mint" >> "$GITHUB_OUTPUT"
        if [ "${RUNNER_OS}" = "Linux" ]; then
          MINT_BINARY=mint-${INPUT_VERSION}-linux
        else
          MINT_BINARY=mint-${INPUT_VERSION}-osx
        fi
        echo "MINT_BINARY=$MINT_BINARY" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Install dependencies
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install rbenv/tap/openssl@1.0
        sudo ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t /usr/local/opt/openssl
        echo "LDFLAGS=\"-L/opt/homebrew/opt/openssl@1.0/lib\"" >> "$GITHUB_ENV"
        echo "CPPFLAGS=\"-I/opt/homebrew/opt/openssl@1.0/include\"" >> "$GITHUB_ENV"
      shell: sh
    - name: Download
      if: ${{ steps.info.outputs.MINT_INSTALLED == 'false' }}
      uses: robinraju/release-downloader@v1.10
      with:
        repository: mint-lang/mint
        latest: false
        tag: ${{ inputs.version }}
        fileName: ${{ steps.info.outputs.MINT_BINARY }}
        tarBall: false
        zipBall: false
        out-file-path: mint
    - name: Install
      if: ${{ steps.info.outputs.MINT_INSTALLED == 'false' }}
      run: |
        mv "${{ steps.info.outputs.MINT_BINARY }}" mint
        chmod +x mint
        echo "${{ steps.info.outputs.MINT_PATH }}" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.MINT_PATH }}
