---
name: "Setup Mint"
author: Yevhen Fabizhevskyi
description: "This action sets up a Mint programming language."
branding:
  icon: feather
  color: green
inputs:
  version:
    description: "Mint version"
    required: false
    default: "0.20.1"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: (runner.os == 'Windows'
        || (runner.os == 'Linux' && startsWith(runner.arch, 'ARM')))
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Collect info
      id: info
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: ./collect-info.sh
      shell: sh
      working-directory: "${{ github.action_path }}/src"
    - name: Download
      if: ${{ steps.info.outputs.mint-installed == 'false' }}
      uses: robinraju/release-downloader@v1.11
      with:
        repository: mint-lang/mint
        latest: false
        tag: ${{ inputs.version }}
        fileName: ${{ steps.info.outputs.mint-binary }}
        tarBall: false
        zipBall: false
        out-file-path: mint
    - name: Install
      if: ${{ steps.info.outputs.mint-installed == 'false' }}
      run: |
        mv "${{ steps.info.outputs.mint-binary }}" mint
        chmod +x mint
        echo "${{ steps.info.outputs.mint-path }}" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.mint-path }}
