---
name: 'Setup Mint'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Mint programming language.'
branding:
  icon: feather
  color: green
inputs:
  version:
    description: 'Mint version.'
    required: false
    default: 0.11.0
runs:
  using: 'node12'
  main: 'dist/index.js'
