name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.ref }}
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: yarn
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        version: ['0.7.1','0.8.0','0.9.0','0.10.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fabasoad/setup-mint-action@v1.0.3
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: mint init ${{ matrix.os }}-${{ matrix.version }}
